### ISSUE TITLE
Gather reasons for deletion of an ad

### ISSUE THREAD

**Issue by radanskoric** [vlado/earthquake-croatia#117]
Now that we have a concept of ad deletion I suggest that it would be useful to gather the reasons for deleting an ad. This information would be valuable in assessing how useful the app is and what needs to be improved to make it more useful. 

The way it would work is that on the page where user needs to confirm page deletion there is also a dropdown where they can select the reason for deletion which is then saved along with the ad as an enum. 

As a start I would propose the following list of reasons:

For "Trazim pomoc" ads:
- Dobili smo pomoc preko ove stranice.
- Dobili smo pomoc preko drugog kanala.
- Sami smo rijesili problem i vise nam ne treba pomoc.
- Ostalo.

For "Nudim pomoc" ads:
- Kontaktirali su nas preko ove stranice i dali smo pomoc.
- Kontaktirali su nas drugim kanalom i dali smo pomoc.
- Vise nismo u mogucnosti ponuditi pomoc.
- Ostalo.

Maybe if "Ostalo" is selected they can enter a free form reason but that could be left for second round of improvements if see a lot of "Ostalo" selections.

Above the reason field I would add a short explanation: "Ova stranica je nastala volonterskim radom i htjeli bi ocijeniti koliko je korisna bila i kako ju mozemo uciniti korisnijom. Pomoglo bi nam kada biste naveli razlog zasto oglas vise nije relevantan. Hvala!"

**Comment by vlado** [comment]
Like it!

**Comment by vlado** [comment]
Also like you idea to send an email asking if ad is still relevant after some time. Not sure if we already have issue for that?

**Comment by radanskoric** [comment]
> Also like you idea to send an email asking if ad is still relevant after some time. Not sure if we already have issue for that?

No, I didn't create an issue for that yet. I'll do that now. But I'd like to do that right after this so we get maximum information out of it.

**Comment by vlado** [comment]
> > Also like you idea to send an email asking if ad is still relevant after some time. Not sure if we already have issue for that?
> 
> No, I didn't create an issue for that yet. I'll do that now. But I'd like to do that right after this so we get maximum information out of it.

Agreed

**Comment by radanskoric** [comment]
I'll get started on this now.
