### ISSUE TITLE
Send a message to the ad author 2 days afterwards to check if the ad is still relevant

### ISSUE THREAD

**Issue by radanskoric** [vlado/earthquake-croatia#121]
In order to ensure that only relevant ads remain I suggest we send a followup e-mail 2 days after the ad has been created asking the author if the ad is still relevant. 

This is the suggested text of the e-mail which I think also clarifies the value of the feature:

"Poštovani,

Dana DD.MM.YYYY objavili ste oglas: link

U svrhu toga da ova stranica bude korisna i da pomoć dođe tamo gdje je potrebna bitno je da su podaci na oglasima ažurni. 

Zbog toga bi vas zamolili da uredite oglas sa novim informacijama ili ga obrišete ako više nije relevantan:

Ovdje možete urediti oglas: link_with_token
Ovdje možete obrisati oglas: link_with_token

Ukoliko ništa ne napravite oglas će naravno i dalje ostati aktivan.

Hvala!"

We can then back send this for the old e-mails. I would suggest storing the last time a reminder e-mail was sent together with the reminder count in case we want to ad multiple reminders later.

This would be best done after https://github.com/vlado/earthquake-croatia/issues/117 to get the biggest information benefit from it.

**Comment by mmorava** [comment]
I love the idea, @radanskoric  will you develop it, if you are busy I can take over this one

**Comment by radanskoric** [comment]
> I love the idea, @radanskoric will you develop it, if you are busy I can take over this one

I plan to develop it, I just want to first finish the PR I started for tests and CI. I know for sure I will not have time today to get started on this one so if you have time sooner go for it.

Just note, I was planning on having that done after https://github.com/vlado/earthquake-croatia/issues/117.

**Comment by radanskoric** [comment]
@mmorava if you still want to, feel free to take this ticket. I opened an MR to implement #117 (https://github.com/vlado/earthquake-croatia/pull/125) but it's not very likely I'll have time to do this ticket today or tomorrow. 

To avoid the complexity of a background processor I think we can simply keep this as a nightly rake task and run it with scheduler addon: https://elements.heroku.com/addons/scheduler

**Comment by vlado** [comment]
Agreed, scheduler should be fine.

**Comment by radanskoric** [comment]
I'll get started on this.

**Comment by vlado** [comment]
> I'll get started on this.

Great!
