### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by vfonic** [vlado/earthquake-croatia#134]
I tried to access the site and I got this error page. I also tried https://potres.herokuapp.com/ with same results.

<img width="1792" alt="Screen Shot 2021-02-16 at 12 24 47" src="https://user-images.githubusercontent.com/67437/108056749-fa5d1c00-7051-11eb-92b2-0e36ce79cc6e.png">

**Comment by vlado** [comment]
@vfonic Thanks for reporting. Will have a look.

**Comment by vlado** [comment]
Since traffic is supper low lately I switched the app to free dynos. Since SNI SSL is not supported on free dynos Strict SSL setting was not working any more. Fixed it by switching to Flexible setting.
