### ISSUE TITLE
Add a section with links to other useful resources

### ISSUE THREAD

**Issue by roja95** [vlado/earthquake-croatia#14]
There are a number of sites offering help to those who suffered in the earthquake and often these sites have links to other sites which are offering the same kind of help. For example https://docs.google.com/document/d/15kSw0O1jtZYTeLh3jZg2XeGFbNbavIBsA0u_PvK8YRs has a link to http://potres.herokuapp.com/ among others so it would be great if they were listed here as well.

**Comment by vlado** [comment]
Sound good. Let's add the link.

**Comment by roja95** [comment]
here is a simple version https://github.com/vlado/earthquake-croatia/pull/15
