### ISSUE TITLE
Add ability to request help

### ISSUE THREAD

**Issue by mmorava** [vlado/earthquake-croatia#35]
after reading some posts on Facebook groups I think it would be a great idea to have ability to put an ad for requesting a help.

App would then have 2 sections , "help requests" and "help offerings"

WDYT?

**Comment by vlado** [comment]
I like the idea. Others?

It was already suggested in Slack channel (by @shime I think).

**Comment by vfonic** [comment]
I love the idea!

We could build on top of that by adding goals, for example, if it's financial aid (that's the easiest), we could have something like on crowdfunding websites.

...which lead me to: Add a list of organizations that accept help/donations #43

**Comment by mmorava** [comment]
OK cool then @vlado  if you can assign to me i will try to write up some tech design doc and send it for a review. once we agree on tech design I'll begin working on implementation

**Comment by shime** [comment]
@mmorava I already have a plan on how to this. Can I take this one or would you like to?

**Comment by mmorava** [comment]
Let's not slow things down then feel free to take it and I'll take something else

**Comment by shime** [comment]
@mmorava thanks!
