### ISSUE TITLE
Improve ad UI and styling

### ISSUE THREAD

**Issue by mmorava** [vlado/earthquake-croatia#36]
At the moment I feel like ads are not quite readable. I would suggest we

1) Present ads in a grid view for better styling while keeping in mind it needs to be mobile first orianted as most of the users probably come from mobile

2) Use some different bootstrap theme with better contrast

**Comment by vlado** [comment]
> At the moment I feel like ads are not quite readable. I would suggest we
> 
> 1. Present ads in a grid view for better styling while keeping in mind it needs to be mobile first orianted as most of the users probably come from mobile

Improvements are welcome for sure.

> 2. Use some different bootstrap theme with better contrast

We are using Bulma https://bulma.io. Let us know what theme you prefer.

**Comment by mmorava** [comment]
I had a look at https://bulmathemes.com/ and I didn't find anything that would impress me. 

Maybe to use https://bulma.style/imperial/dist/ui-elements.html and customize it a bit to have better contrast as a lot of older people would be using the app

**Comment by Macxim** [comment]
I can help with this 🙋

**Comment by vlado** [comment]
Thanks @Macxim
