### ISSUE TITLE
Setup domain

### ISSUE THREAD

**Issue by mmorava** [vlado/earthquake-croatia#37]
I suggest we setup a more human-readable domain like for example pomocupotresu.com . If project lead agrees I volunteer to buy and setup it 

Also we should then setup site to be HTTPS only and setup a https certificate through heroku as some browsers maybe prevent users from reaching the site over http.

**Comment by vlado** [comment]
I was thinking that this would be helpful in other crisis also (floods, ...) so I think we need more general name. Like `kriza.hr`, Flow and Form team is also working on some naming and branding ideas.

I'm waiting response from Carnet if we can get `.hr` domain for free.

**Comment by mmorava** [comment]
@vlado  I was thinking the same way however as I know it takes time to get a proper domain name I thought of this as a quick improvement and later on we can always set up 301 redirect to the new "permanent" domain name?

**Comment by vlado** [comment]
We should have `.hr` domain today probably.

**Comment by markopavlovic** [comment]
`pomozi.hr` is reserved now for us

**Comment by vlado** [comment]
We have potres-petrinja.hr also. Will take care of it now.

**Comment by markopavlovic** [comment]
@vlado shoild we move this to done for now?

**Comment by vlado** [comment]
> @vlado shoild we move this to done for now?

Let's wait for https://github.com/vlado/earthquake-croatia/pull/65 to be merged.
