### ISSUE TITLE
Organize a Trello board

### ISSUE THREAD

**Issue by mmorava** [vlado/earthquake-croatia#38]
I suggest we organize a Kanban for this project, probably thorough Trello as it is the most simple solution to sign up and manage.

We should use trello instead of Github issues to  create a project backlog, discuss tasks before execution and follow the tasks through executions. If author agrees i will take care of setting up a board

**Comment by markopavlovic** [comment]
@mmorava added https://github.com/vlado/earthquake-croatia/projects/1
I think should be enough and we'd prefer it to have as much as possible in a single place.
Thoughts?

**Comment by vlado** [comment]
I agree with @markopavlovic, let's keep thins simple and in one place.
