### ISSUE TITLE
Should we add Rubocop?

### ISSUE THREAD

**Issue by vlado** [vlado/earthquake-croatia#44]
There are lot of us now and Rubocop could save time when reviewing PRs. I hope this will not turn into which rules to use war :)

**Comment by vfonic** [comment]
Let's add it and setup CI.

We should pick some config and just stick to it.
If anyone has a really good reason to add/change/remove a rule, then let's hear it.

I don't see anyone complaining about using Bulma. I'm ok if you just pick one config and we stick to it from now on.

**Comment by shime** [comment]
Closed by 61d94262672e9384801. 

This config shouldn't be too strict.
