### ISSUE TITLE
Only icon inside of 'Lokacija na karti' is clickable

### ISSUE THREAD

**Issue by Xenosb** [vlado/earthquake-croatia#52]
As a user I'd like to click anywhere inside of the action button
As a user, I'd like to have the whole button change color when hovered over

![image](https://user-images.githubusercontent.com/1616329/103410564-2c7ef100-4b6c-11eb-9630-4b1bf24e0af2.png)

**Comment by markopavlovic** [comment]
👍 cc @vlado

**Comment by vlado** [comment]
👍
