### ISSUE TITLE
Move useful links to a more suitable location

### ISSUE THREAD

**Issue by Xenosb** [vlado/earthquake-croatia#56]
As a user I'd like to see useful links and documents first or as a link to separate page/div

Currently, user needs to scroll through 50 ads to see the useful links/docs. With #55 this would be a bit better but not solved. My recommendation would be to add a 🍔 menu and a separate page or a link at the top which leads to the div.

![IMG_EE51B95253D8-1](https://user-images.githubusercontent.com/1616329/103411030-47eafb80-4b6e-11eb-9c79-1f2aa854ba83.jpeg)

**Comment by vlado** [comment]
We need some general idea for menu/navbar.
