### ISSUE TITLE
Add real hero section

### ISSUE THREAD

**Issue by Macxim** [vlado/earthquake-croatia#69]
I have a suggestion. I'll post something quickly.

**Comment by Macxim** [comment]
Thoughts?

<img width="1440" alt="Screen Shot 2020-12-31 at 20 00 25" src="https://user-images.githubusercontent.com/1909957/103424190-daa58d80-4ba2-11eb-8c77-ef81cffbf224.png">

**Comment by vlado** [comment]
Thanks!

👍 Let's see what others say.

**Comment by shime** [comment]
I like it! Looks better than what we currently have.
