### ISSUE TITLE
Make hero a bit smaller, it takes half the fold on a 15" screen

### ISSUE THREAD

**Issue by berislavbabic** [vlado/earthquake-croatia#90]
Hero is too tall, it should take less screenspace

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/418219/103466994-9f45c300-4d4a-11eb-8cd9-52552755b3c1.png">

**Comment by Macxim** [comment]
Easy as removing the `is-medium` class here: https://github.com/vlado/earthquake-croatia/blob/1fbcfcd5dd0bb400679b3b5d18bdccf4b44e8aba/app/views/layouts/application.html.erb#L26

Can you take it?

**Comment by berislavbabic** [comment]
yup, I'm on it
