### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by vlado** [vlado/earthquake-croatia#95]
We are including jQuery https://github.com/vlado/earthquake-croatia/blob/master/app/views/layouts/application.html.erb#L10 and I think it is only used here https://github.com/vlado/earthquake-croatia/blob/master/app/javascript/controllers/filter_controller.js#L32-L38

Should be easy to remove it.

**Comment by vlado** [comment]
Let's wait with this. We will probably use `select2` for cities select and it requires jQuery.

**Comment by vfonic** [comment]
Let's close this and focus on other things in the meantime. We use select2 which is a jQuery plugin so we can't remove it just like that.

**Comment by radanskoric** [comment]
> Let's close this and focus on other things in the meantime. We use select2 which is a jQuery plugin so we can't remove it just like that.

I agree and also for this particular project we maybe even want jQuery. I know it's not modern and it's on its way out but it still has the largest amount of well crafted UI libraries relying on it. From a pragmatic point of view we probably want to keep it anyway.

Closing it.
